### ISSUE TITLE
Host not working on eu-south-1

### ISSUE THREAD

**Issue by morninger** [quarfie/s3presignedUrl_FMFunction#4]
Hi,
when creating a bucket on region **eu-south-1** (Milan) the code used to determine the host is not working because the dash is not accepted.
I got it working replacing it with a dot.

So instead of

  ~host = If ( IsEmpty ( ~optionsHost ) ; ~bucket & ".s3" & If ( ~region ≠ "us-east-1" ; "-" & ~region ) & ".amazonaws.com" ; ~optionsHost ) ;

I used the following and it works.
  ~host = If ( IsEmpty ( ~optionsHost ) ; ~bucket & ".s3" & If ( ~region ≠ "us-east-1" ; "." & ~region ) & ".amazonaws.com" ; ~optionsHost ) ;

Hope it helps.

Ciao, Riccardo Albieri

**Comment by bossroom** [comment]
Hey Rick, this is a duplicated: https://github.com/quarfie/s3presignedUrl_FMFunction/issues/3#issue-1560061886

**Comment by morninger** [comment]
Ooops, sorry about that.
